---
title: "Assignment 1 : Linear Regression"
output: html_document
date: "2023-11-29"
---


Importing packages
```{r, message = FALSE}
install.packages("ggmice")
library(dplyr)
library(readr)
library(knitr)
library(kableExtra)
library(DT)
library(ggplot2)
library(ggmice)
```

Reading in the datasets
```{r, message = FALSE}
n_em <- read_csv("data/nitrous-oxide-emissions.csv", show_col_types = FALSE) %>%
  filter(Year == 2020)

#n_em_per_cap <- read_csv("data/per-capita-nitrous-oxide.csv") %>%
  #filter(Year == 2020)
#n_em_per_cap

n_em_per_sec <- read_csv("data/per-capita-nitrous-oxide-sector.csv") %>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
pop_den <- read_csv("data/population-density.csv")%>%
  filter(Year == 2020) %>% 
  select(-Year,- Code)
forest_area <- read_csv("data/population-density.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
gdp_per_cap <- read_csv("data/gdp-per-capita-worldbank.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
meat_supp_per_cap <- read_csv("data/meat-supply-per-person.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
n_fert_app_per_hect <- read_csv("data/nit_fert_app.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
agr_land <- read_csv ("data/agricultural-land.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
ann_growth_exp <- read_csv("data/annual-growth-of-exports-of-goods-and-services.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
ann_growth_imp <- read_csv("data/annual-growth-of-imports-of-goods-and-services.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
urban_v_rural <- read_csv("data/urban-vs-rural-majority.csv")%>%
  filter(Year == 2020)%>% 
  select(-Year,- Code)
#water_resc <- read_csv("data/renewable-water-resources-per-capita.csv")%>%
 #filter(Year == 2020)%>% 
# select(-Year,- Code)#only goes upto 2019 
#wetlands <- read_csv("data/coverage-of-wetlands.csv") #only went up to 2017 
```

Merging the datasets
```{r, message = FALSE}
df <- n_em %>%
  left_join(pop_den, by = "Entity") %>%
  left_join(n_em_per_sec, by = "Entity")%>%
  left_join(forest_area, by = "Entity")%>%
  left_join(gdp_per_cap, by = "Entity") %>%
  left_join(meat_supp_per_cap, by = "Entity")%>%
  left_join(n_fert_app_per_hect, by = "Entity") %>%
  left_join(agr_land, by = "Entity")%>%
  left_join(ann_growth_exp, by = "Entity") %>%
  left_join(ann_growth_imp, by = "Entity")%>%
  left_join(urban_v_rural, by = "Entity")%>%
# left_join(water_resc, by = "Entity") %>%
  select(-"Population density.x", - "Year")
```
Renaming some columns 
```{r}
colnames(df)[4:7] <- c("Agriculture Waste Emissions", "Waste Emissions", "Land Use Change and Forestry", "Energy Production Emissions")
colnames(df)[15:16] <- c("% Urban Population", "% Rural Population")
df
```
Creating a categorical column based on the predominant nitrogen emission sector 
```{r}
df <- df %>% 
  mutate("Highest Emission Sector" = case_when(
    `Agriculture Waste Emissions` >
      `Waste Emissions` & `Agriculture Waste Emissions` > 
      `Land Use Change and Forestry` & `Agriculture Waste Emissions` > 
      `Energy Production Emissions` ~ 
      "Agriculture Waste",
    `Waste Emissions` > 
      `Agriculture Waste Emissions` & `Waste Emissions` > 
      `Land Use Change and Forestry` & `Waste Emissions` > 
      `Energy Production Emissions` ~ 
      "Waste Emissions",
    `Land Use Change and Forestry` > 
      `Agriculture Waste Emissions` & `Land Use Change and Forestry` > 
      `Waste Emissions` & `Land Use Change and Forestry` > 
      `Energy Production Emissions` ~ 
      "Land Use Change and Forestry",
    `Energy Production Emissions` > 
      `Agriculture Waste Emissions` & `Energy Production Emissions` > 
      `Land Use Change and Forestry` & `Energy Production Emissions` > 
      `Waste Emissions` ~ 
      "Energy Production",
    TRUE ~ NA_character_
  ))
df

```

Creating a binary variable depending on whether the majority of population lives in urban or rural areas
```{r}
df <- df %>%
  mutate("Majority Population( Urban/Agricultural" = case_when(
    `% Urban Population` > `% Rural Population` ~ "Urban",
    `% Rural Population` > `% Urban Population` ~ "Rural"
  ))

df

```

Initial exploratory analysis using graphs

```{r}
# Relationship between population density and nitroxide emissions 

p1 <- ggplot(data = df, aes(
  x = `Annual nitrous oxide emissions in CO₂ equivalents`,
  y = `Population density.y`
)) +
geom_point() + 
ylim(0, 2500)

p1

# Relationship between GDP and nitroxide emissions 

p2 <- ggplot(data = df, aes(
  x = `Agriculture Waste Emissions`,
  y = `GDP per capita, PPP (constant 2017 international $)`
)) +
geom_point() + 
ylim(0, 5000)

p2

```
kjsdkas
